name: visitor_pass
description: A new Flutter project.

publish_to: "none"
version: 1.0.3+4

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  http: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.0.9
  dropdown_button2: ^2.3.9
  get_storage: ^2.0.3
  flag: ^7.0.0
  shimmer: ^3.0.0
  printing: ^5.12.0
  email_validator: ^3.0.0
  dropdown_search: ^6.0.1
  flutter_screenutil: ^5.6.0
  mobile_scanner: ^6.0.2
  permission_handler: ^11.0.1
  google_fonts: ^6.1.0
  intl_phone_field: ^3.2.0
  win32: ^5.5.3
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  archive: 4.0.7
  firebase_core: ^4.1.0
  clarity_flutter: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.jpg"
  remove_alpha_ios: true
  adaptive_icon_background: "#E3256B"    # your brand color
  adaptive_icon_foreground: "assets/images/app_logo.jpg"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/app_logo.jpg
  android: true
  ios: true

  android_12:
    color: "#FFFFFF"
    image: assets/images/app_logo.jpg

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/home/


